name: Black

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "-l 99 --check ."
