name: Black Code Formatter Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter Check
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "--check ."
